language: ruby
rvm:
- 2.3.1
sudo: false
install:
- bundle install
script: bundle exec rake deploy
env:
  global:
    secure: sok1bjLbtCJLQehvmH/SoBcvkVIvJ6Vi6Cx5vuffQowuYeNPv5NNCflVAwDiSSl4mkjRCRZEYxc7K1iZfB9S8sXB0jn7BjYWZfz3zFK29YQyCz0K6ARoJWYOmHKxtowylghPad9YMDmgaD0fp+Z1T6zlY0A+zyuNbJNihZX00xI=
